name: CI pipeline

on:
  push:
    branches:
      - lab3
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd app_python
          pipenv install --dev

      - name: Lint with flake8
        run: |
          cd app_python
          pipenv run flake8

      - name: Test with pytest
        run: |
          cd app_python
          pipenv run pytest

      - name: Install snyk
        run: npm install -g snyk

      - name: Login to Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Test with Snyk
        run: |
          cd app_python
          snyk test --file=requirements.txt --command=python3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          cd app_python
          docker build -t tatarinalba/devops:1.0 .
          docker push tatarinalba/devops:1.0