name: CI pipeline

on:
  push:
    branches:
      - lab3
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: cd app_python && pipenv install --dev
      - name: Lint with flake8
        run: cd app_python && pipenv run flake8
      - name: Test with pytest
        run: cd app_python && pipenv run pytest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: tatarinalba/devops:1.0