name: CI pipeline

on:
  push:
    branches:
      - lab3
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          cd app_python
          pipenv install --dev

      - name: Lint with flake8
        run: |
          cd app_python
          pipenv run flake8

      - name: Test with pytest
        run: |
          cd app_python
          pipenv run pytest

  security:
    needs: build
    timeout-minutes: 1

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pipenv
        run: |
          pip install pipenv
          export PATH="$PATH:$HOME/.local/bin"

      - name: Verify Pipenv Installation
        run: |
          pipenv --version

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        with:
          args: --skip-unresolved app_python/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  docker_build:
    runs-on: ubuntu-latest
    needs:
      - build
      - security
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          cd app_python
          docker build -t tatarinalba/devops:1.0 .
          docker push tatarinalba/devops:1.0